# Ansible Inventory - Generated by Terraform
# DO NOT EDIT MANUALLY - This file is auto-generated

all:
  hosts:
    video_server:
      ansible_host: "${public_ip}"
      ansible_user: ubuntu
      ansible_connection: ssh
      ansible_port: 22
      ansible_ssh_private_key_file: "~/.ssh/id_rsa"
      ansible_python_interpreter: /usr/bin/python3

  vars:
    # Instance information
    instance_id: "${instance_id}"
    instance_type: "${instance_type}"
    availability_zone: "${availability_zone}"

    # Storage
    models_volume_id: "${models_volume_id}"
    output_volume_id: "${output_volume_id}"

    # Application directories
    app_dir: /home/ubuntu/video-generation
    models_dir: /mnt/models
    output_dir: /mnt/output
